#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Packaging step: record the build date and the SHA-256 of the test engine in bc250_gui/_build_info.py.

With that file present the app runs as a release build: before every run it refuses a test engine that
does not have exactly this checksum, or that is not owned by root and writable by root only.
Run it after the last change to test-bazzite.sh, from the repository root:

    python3 development/tools/build_info.py            # or: python3 development/tools/build_info.py --remove  (back to development)
"""

import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ENGINE = ROOT / "test-bazzite.sh"
TARGET = ROOT / "bc250_gui" / "_build_info.py"


def main() -> int:
    if "--remove" in sys.argv:
        TARGET.unlink(missing_ok=True)
        print(f"Removed {TARGET}: development mode.")
        return 0
    digest = hashlib.sha256(ENGINE.read_bytes()).hexdigest()
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    TARGET.write_text('"""Generated by development/tools/build_info.py at packaging time. Do not edit."""\n\n'
                      f'BUILD_DATE = "{date}"\n'
                      f'SCRIPT_SHA256 = "{digest}"\n', encoding="utf-8")
    print(f"{TARGET.relative_to(ROOT)}: engine SHA-256 {digest}, build date {date}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
